# Generated by Django 5.1 on 2024-11-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0008_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='submitted_time',
        ),
    ]
